.github/workflows/ci.yml
.github/workflows/commitlint.yml

- removed extra commit-lint step
- added commitlint as core CI step

fix: remove extra commit-lint step

---

pyproject.toml
src/uipath_langchain/tracers/__init__.py
src/uipath_langchain/tracers/_instrument_traceable.py
uv.lock

New method to replace `@traced()` decorator implementation

feat(trace): fix tracing integration with sdk

---

docs/interrupt_models.md
samples/company-research-agent/graph.py
samples/multi-agent-planner-researcher-coder-distributed/pyproject.toml
samples/multi-agent-planner-researcher-coder-distributed/src/multi-agent-distributed/coder.py
samples/multi-agent-planner-researcher-coder-distributed/src/multi-agent-distributed/planner.py
samples/multi-agent-planner-researcher-coder-distributed/src/multi-agent-distributed/researcher.py
samples/multi-agent-planner-researcher-coder-distributed/uv.lock
samples/multi-agent-supervisor-researcher-coder/graph.py

- use ainvoke in samples
-  improve interrupt models docs

chore: use ainvoke in samples, improve interrupt models docs

---

pyproject.toml
src/uipath_langchain/_cli/cli_init.py
uv.lock

- add spinner for init command

feat: add spinner for init command

---

pyproject.toml
src/uipath_langchain/_cli/_templates/langgraph.json.template
src/uipath_langchain/_cli/_templates/main.py.template
src/uipath_langchain/_cli/cli_new.py
src/uipath_langchain/middlewares.py
uv.lock

feat: add new cli command

---

pyproject.toml
src/uipath_langchain/_cli/cli_init.py
src/uipath_langchain/_cli/cli_new.py
uv.lock

fix: use ConsoleLogger

---

pyproject.toml
src/uipath_langchain/tracers/_instrument_traceable.py

```toml
[project]
"uipath-langchain-nightly==0.0.95.dev1000470003",
"uipath-langchain-nightly>=0.0.95.dev1000470000,<0.0.95.dev1000480000"
]
```

feat(tracer): add support for custom names on traced

---

docs/human_in_the_loop.md
pyproject.toml
samples/multi-agent-planner-researcher-coder-distributed/README.md
samples/ticket-classification/README.md
src/uipath_langchain/_cli/_templates/main.py.template
src/uipath_langchain/_cli/cli_run.py
uv.lock

- samples improvements
- removed 'Error' string from template message `❌ Error: Error: Missing API Key. Please define either ANTHROPIC_API_KEY or OPENAI_API_KEY.`

chore: samples improvements

---

pyproject.toml
src/uipath_langchain/_cli/cli_new.py
uv.lock

chore: usage example new agent

---

pyproject.toml
src/uipath_langchain/retrievers/context_grounding_retriever.py
uv.lock

- folder support for ContextGroundingRetriever

feat: folder support for ContextGroundingRetriever

---

pyproject.toml
src/uipath_langchain/_cli/_runtime/_output.py
uv.lock

- insert trigger in state.db for defaultEscalations
```toml
[project]
"uipath-langchain-nightly==0.0.107.dev1000740073",
"uipath-langchain-nightly>=0.0.107.dev1000740000,<0.0.107.dev1000750000"
]
```

fix: insert trigger in state.db for defaultEscalations

---

pyproject.toml
src/uipath_langchain/tracers/AsyncUiPathTracer.py

Add better logging for `Exception when sending trace: .`

feat(logging): add more trace exceptions

---

docs/quick_start.md

- quick start docs improvements

chore: quick start docs improvements

---

samples/multi-agent-planner-researcher-coder-distributed/pyproject.toml
samples/multi-agent-supervisor-researcher-coder/pyproject.toml
samples/simple-local-mcp/README.md

- remove extra list from samples pyproject authors

fix: samples pyproject authors

---

src/uipath_langchain/_cli/_runtime/_runtime.py

```toml
[project]
"uipath-langchain-nightly==0.0.110.dev1000870113",
"uipath-langchain-nightly>=0.0.110.dev1000870000,<0.0.110.dev1000880000"
]
```

fix: pretty print debug runs

---

samples/simple-local-mcp/pyproject.toml
samples/simple-local-mcp/src/simple-local-mcp/graph.py
samples/simple-local-mcp/uipath.json
samples/simple-local-mcp/uv.lock

- new usage for MultiServerMCPClient
fixed `langchain-mcp-adapters` [breaking change](https://github.com/langchain-ai/langchain-mcp-adapters/releases)

fix: new usage for MultiServerMCPClient

---

pyproject.toml
src/uipath_langchain/_utils/_settings.py

fix for https://github.com/UiPath/uipath-python/issues/401

fix(llm): set default header values fix #401

---

pyproject.toml

Changed project version to `0.0.111` (`>0.0.110 ` versions were not published due to CD issues)

chore: change version

---

pyproject.toml
src/uipath_langchain/vectorstores/context_grounding_vectorstore.py

- added folderpath parameter to vectorstore constructor

chore: vectorstore folder support

---

pyproject.toml
uv.lock

chore: bump version

---

pyproject.toml
src/uipath_langchain/chat/models.py

Update UiPath chat to proper endpoint
```toml
[project]
"uipath-langchain==0.0.118.dev1001290304",
"uipath-langchain>=0.0.118.dev1001290000,<0.0.118.dev1001300000"
]
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
[tool.uv.sources]
uipath-langchain = { index = "testpypi" }
```

fix(chat): fix uipath chat endpoint

---

src/uipath_langchain/builder/agent_config.py
tests/builder/test_config.py

This PR introduces agent builder configuration models to enable structured handling of agent configurations. The implementation uses Pydantic models to define the schema for agent components including messages, settings, and various resource types.
- Adds comprehensive Pydantic models for agent configuration with support for tools, context, and escalation resources
- Implements discriminated unions for type-safe resource handling
- Provides extensive test coverage with a complete JSON configuration example

feat: add agent builder config models

---

samples/company-research-agent/graph.py

LangGraph has different output formats based on the streaming mode of the graph ("updates" vs "messages")
Ref: https://github.com/langchain-ai/langgraph/issues/2698

fix: sample safe extract text

---

pyproject.toml
src/uipath_langchain/_cli/_runtime/_context.py
src/uipath_langchain/_cli/cli_eval.py
src/uipath_langchain/_cli/cli_run.py
src/uipath_langchain/middlewares.py
uv.lock

- add eval middleware
```toml
[project]
"uipath-langchain==0.0.128.dev1001690512",
"uipath-langchain>=0.0.128.dev1001690000,<0.0.128.dev1001700000"
]
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
[tool.uv.sources]
uipath-langchain = { index = "testpypi" }
```

feat: add eval middleware

---

pyproject.toml

```toml
[project]
"uipath-langchain==0.0.130.dev1001730521",
"uipath-langchain>=0.0.130.dev1001730000,<0.0.130.dev1001740000"
]
[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
[tool.uv.sources]
uipath-langchain = { index = "testpypi" }
```

fix: increment core version

---

.github/workflows/integration_tests.yml
testcases/common/print_output.sh
testcases/company-research-agent/pyproject.toml
testcases/company-research-agent/run.sh
testcases/multi-agent-supervisor-researcher-coder/pyproject.toml
testcases/multi-agent-supervisor-researcher-coder/run.sh
testcases/simple-local-mcp/pyproject.toml
testcases/simple-local-mcp/run.sh
testcases/ticket-classification/pyproject.toml
testcases/ticket-classification/run.sh

- fix a problem where testcases asserts were not propagated to job output
- revert to one job per testcase
- small refactor to run.sh

fix(testcases): refactor and fix testcases
